### ISSUE TITLE
CGI Error at certinfo.gmi

### ISSUE THREAD

**Issue by cheeesy** [MineRobber9000/stream-of-consciousness#2]
I tried it with elpher and AV-98, both return a CGI error when trying to connect to certinfo.gmi with a loaded certificate.

The certificate is not put into the accepted hashes list either.

Any idea on how to fix it (using a different client maybe?) or adding the hash manually?

Server is gemserv

**Comment by MineRobber9000** [comment]
Ah. Your cert must not have had a CN. This will be fixed in the next commit.

**Comment by cheeesy** [comment]
Thanks very much!

Yeah, I worded that a bit bad. What I meant is that it didn't display a hash for me to add :P
